# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1


#TEMPLATE INFO: Remember to fix the below repo path and remove this comment
image:
  repository: ghcr.io/energinet-singularity/dlr-mrid/energinet-singularity/dlr-mrid
  pullPolicy: IfNotPresent
  tag: "0.0.11"

#Setup file-mover dependency first
dlrmridInputVolume: 
  persistentVolumeClaim:
    claimName: dlr-mrid-pvc

dlrmridDataVolume:
  accessMode: ReadWriteOnce
  size: 100M
  storageClass: standard

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:      
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: dlr-mrid-pvc
  podLabels:
    dlr-mrid-filemover: "S1"
  selectorLabels:
    dlr-mrid-filemover: "S1"
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: dlr-mrid
                operator: In
                values:
                - S1
          topologyKey: "kubernetes.io/hostname"
          
podLabels:
  dlr-mrid: "S1"
selectorLabels:
  dlr-mrid: "S1"
affinity:
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: dlr-mrid-filemover
              operator: In
              values:
              - S1
        topologyKey: "kubernetes.io/hostname"
        
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []

file:
  name: ""
database:
  expose: ""
cycle:
  time: ""
use:
  mock:
    data: ""
