# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

#TEMPLATE INFO: Remember to fix the below repo path and remove this comment
image:
  repository: ghcr.io/energinet-singularity/dlr-mrid/energinet-singularity/dlr-mrid
  pullPolicy: IfNotPresent
  tag: "0.0.9"

#Setup file-mover dependency first
dlrmridInputVolume: 
  persistentVolumeClaim:
    claimName: dlr-mrid-pvc

dlrmridDataVolume:
  accessMode: ReadWriteOnce
  size: 10M
  storageClass: standard

file-mover:
  folderMounts:
    input:
      enabled: true
      volume:
        emptyDir: {}
    output:
      enabled: true
      volume:
        persistentVolumeClaim:
          claimName: dlr-mrid-pvc

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
nodeSelector: {}
tolerations: []
